# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49411cd8dcd4d11f90a97107c68413fabb7a06b8a1d44535b49e22bfa23f6f6e4bbf69e2e8f83959e61b29f1a6a0258cce0c0bb9938a8fb9cd0150efc3dff0d9

test:
  secret_key_base: 89a4fdd2447340e291307a5fbdf016ac75d0d04536ea180cb9d04017ee6a2efe07532bc358486cc55f49cfeddc6f84f23fa7635a39e4d79990c591dad01ef21c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
